### PR TITLE
Add Windows default command

### PR DESCRIPTION
**Pull request by daipom**
I am still in the process of implementing this feature.

TODO

- [X] remove the empty lines from io
- [X] consider adjusting DEFAULT_KEYS for Windows
- [X] consider simplifying default ps command for Windows, and separate plugin if need
- [ ] fix README
- [ ] create test code

### CODE REVIEW

**Comment by ashie** [comment]
> TODO

FYI: I prefer using checkboxes for TODO list:
https://docs.github.com/ja/github/managing-your-work-on-github/about-task-lists
e.g.) https://github.com/fluent-plugins-nursery/td-agent-builder/pull/288

**Comment by kenhys** [comment]
https://github.com/daipom/fluent-plugin-watch-process/pull/1/commits/6fedf384eaeb482a4c4f14622a2ac5b8afc29deb

It seems that too many changes are done in one commit.

```
- Fix Windows command simpler.
- Separate `keys` and `types` settings for each OS.
- Stop calclulating `elapsed_time` in Windows logic.
```

When you need to explain changes in multiple paragraphs, IMHO it is a signal to
split in multiple commits in meaningful unit.

**Comment by daipom** [comment]
@kenhys
Thank you for the advice.
I also think this is too big commit.

Stopping adapting to the Unix ps format and simplifying the Windows commands were inseparable,
and this made it difficult to separate the commit.

I should have separated the commit in the part where I refactor the existing logic into `Watcher` module.

**Comment by daipom** [comment]
Hmm, I think I should recreate the branch to make the history easy to understand.

**Comment by daipom** [comment]
I recreate pull request to [Support windows](https://github.com/daipom/fluent-plugin-watch-process/pull/2).

**Pull request closed without merging**
